### PR TITLE
Add support for CollabNet's TeamForge

### PR DESCRIPTION
**Pull request by tommyd3mdi**
I added basic support for TeamForge 5.4 that (unfortunately) we're forced to use here. The bookmarklet only works on list views of this tracker, not detail views, and evaluates the columns "Artifact ID : Title", "Description", and "Assigned To", which must be selected in the current column configuration (I throw a user-visible exception if one of them is missing).

On the same run I had to make a couple of tweaks:
* Since old TeamForge installations (5.4 dates back to 2011, but is still in production) still used an oldish jQuery (1.3), not all things were available. `$.on` is one example, which I forwarded to the (deprecated) `$.bind`. `$.bind('input')` was also not available, but `$.change()` works exactly the same as well.
* I changed the way authors are represented when no avatar is available (TeamForge has no avatar concept), so now not the first letter, but all first letters of all names are used ("Joe User" -> "JU"). On the same run I removed the default background image ("the elf") so that this is actually properly visible.
* Finally, I couldn't stand the naming issues with "instalation", so I renamed a couple of things :)

Be aware that you do not apply this PR without changing the absolute paths for gh-pages from `tommyd3mdi....` back to `qoomon...`.

### CODE REVIEW

**Comment by qoomon** [comment]
thx a lot. i will review it later this week

**Comment by tommyd3mdi** [comment]
Thank you!

**Comment by tommyd3mdi** [comment]
Hrm... I guess you should back-out the last change, in 2c94a62, because I had to disable Google Analytics in my fork because of company policies, and that might not be what you wanted (beside that it creates script issues because I did not do it fully).

**Comment by qoomon** [comment]
I didn't merge this commit. tanks anyway.
May you can check if my script now works you too? 
I also adjust the style a bit.
I am looking forward for your feedback

**Comment by tommyd3mdi** [comment]
Ah, thats awesome, properly colored tags! Nice, it works for me perfectly!

**Pull request merged**
